### PR TITLE
Dci create component

### PR DESCRIPTION
**Pull request by tonyskapunk**
Using dci-create-component
Bump version to 1.0.0
Update Documentation with required changes

### CODE REVIEW

**Comment by tonyskapunk** [comment]
Test in: https://github.com/tonyskapunk/test-dci-component/actions/runs/3091606163

**Review by manurodriguez — APPROVED** [review]
This looks good to me, just a couple of questions, since I'm not really into the github actions
What is the use case or when is helpful to use this dci-component action? 
I was only aware of the cli option[1], but I'm thinking when would be appropriate to use this action?
Thanks!
[1] https://docs.distributed-ci.io/python-dciclient/#dci-create-component

**Comment by tonyskapunk** [comment]
> What is the use case or when is helpful to use this dci-component action? 

This is a way to ease the creation of components when someone using DCI may be using GHA as part of its CI. For example, in this project [rh-nfv-int/nfv-example-cnf-index](https://github.com/rh-nfv-int/nfv-example-cnf-index/blob/master/.github/workflows/quay.yml#L36-L37) we use GHA to release the catalog of operators, using this dci-component GHA, makes easier to create the component at that time as well.

> I was only aware of the cli option[1], but I'm thinking when would be appropriate to use this action? Thanks! [1] https://docs.distributed-ci.io/python-dciclient/#dci-create-component

This GHA was initially under my account, but I've moved to this org few days back. In the past it was using [dcictl](https://github.com/redhat-cip/python-dciclient#python-dciclient) another tool that's provided with the python-dciclient package. But, since we've created `dci-create-component` to make easier the creation of components, then in this change I'm making use of that tool instead.

hth

**Comment by manurodriguez** [comment]
> > What is the use case or when is helpful to use this dci-component action?
> 
> This is a way to ease the creation of components when someone using DCI may be using GHA as part of its CI. For example, in this project [rh-nfv-int/nfv-example-cnf-index](https://github.com/rh-nfv-int/nfv-example-cnf-index/blob/master/.github/workflows/quay.yml#L36-L37) we use GHA to release the catalog of operators, using this dci-component GHA, makes easier to create the component at that time as well.

Thanks for the clarification, I see when is helpful to use this method.

**Review by betoredhat — APPROVED** [review]
:trophy: LGTM

**Pull request merged**
